version: '3'
services:
  backend: 
    build:
      context: ./
      args:
        - NODE_ENV=${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_PORT=${SERVER_PORT}
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always

